import React from 'react';

export default () => {
  return (
    <div>
      <h2>Privacy Policy</h2>
      <p>Last updated: May 01, 2018</p>
      <p>
        Online Sales Pro, by LeadLine, LLC ("us", "we", or "our") operates the{' '}
        <a href="https://onlinesalespro.com">https://onlinesalespro.com</a>{' '}
        website and the Online Sales Pro mobile application (the "Service").
      </p>
      <p>
        This page informs you of our policies regarding the collection, use, and
        disclosure of personal data when you use our Service and the choices you
        have associated with that data. We use your data to provide and improve
        the Service. By using the Service, you agree to the collection and use
        of information in accordance with this policy. Unless otherwise defined
        in this Privacy Policy, terms used in this Privacy Policy have the same
        meanings as in our Terms and Conditions.
      </p>
      <h2>Definitions</h2>
      <p>
        <strong>Personal Data</strong>
      </p>
      <p>
        Personal Data means data about a living individual who can be identified
        from those data (or from those and other information either in our
        possession or likely to come into our possession).
      </p>
      <p>
        <strong>Usage Data </strong>
      </p>
      <p>
        Usage Data is data collected automatically either generated by the use
        of the Service or from the Service infrastructure itself (for example,
        the duration of a page visit).
      </p>
      <p>
        <strong>Cookies </strong>
      </p>
      <p>Cookies are small pieces of data stored on a User’s device.</p>
      <p>
        <strong>Customer </strong>
      </p>
      <p>Customers are members using the Service for lead generation.</p>
      <p>
        <strong>Data Controller </strong>
      </p>
      <p>
        Data Controller means a person who (either alone or jointly or in common
        with other persons) determines the purposes for which and the manner in
        which any personal data are, or are to be, processed. For the purpose of
        this Privacy Policy, we are a Data Controller of your data when you are
        a customer using our Service.
      </p>
      <p />
      <p>
        <strong>Data Processor (or Service Providers) </strong>
      </p>
      <p>
        Data Processor (or Service Provider) means any person (other than an
        employee of the Data Controller) who processes the data on behalf of the
        Data Controller. We may use the services of various Service Providers in
        order to process your data more effectively.
      </p>
      <p>
        <strong>Data Subject </strong>
      </p>
      <p>
        Data Subject is any living individual who is the subject of Personal
        Data.
      </p>
      <p>
        <strong>User </strong>
      </p>
      <p>
        The User is the individual using our Service. The User corresponds to
        the Data Subject, who is the subject of Personal Data.
      </p>
      <p>
        <strong>Information Collection And Use </strong>
      </p>
      <p>
        We collect several different types of information for various purposes
        to provide and improve our Service to you.
      </p>
      <h2>Types of Data Collected </h2>
      <p>
        <strong>Personal Data </strong>
      </p>
      <p>
        While using our Service as a customer, we may ask you to provide us with
        certain personally identifiable information that can be used to contact
        or identify you ("Personal Data"). Personally identifiable information
        may include, but is not limited to:
      </p>
      <p>- Email address</p>
      <p>-First name and last name</p>
      <p>-Phone number</p>
      <p>-Address, State, Province, ZIP/Postal code, City, Country</p>
      <p>-Cookies and Usage Data</p>
      <p>
        We may use your Personal Data to contact you with newsletters, marketing
        or promotional materials and other information that may be of interest
        to you. You may opt out of receiving any, or all, of these
        communications from us by following the unsubscribe link or instructions
        provided in any email we send or by contacting us.
      </p>
      <p>
        By providing your email address on our checkout page and moving to the
        next step, you are consenting to receiving marketing material about our
        services.
      </p>
      <p>
        <strong>Usage Data </strong>
      </p>
      We may also collect information that your browser sends whenever you visit
      our Service or when you access the Service by or through a mobile device
      ("Usage Data"). This Usage Data may include information such as your
      computer's Internet Protocol address (e.g. IP address), browser type,
      browser version, the pages of our Service that you visit, the time and
      date of your visit, the time spent on those pages, unique device
      identifiers and other diagnostic data. When you access the Service by or
      through a mobile device, this Usage Data may include information such as
      the type of mobile device you use, your mobile device unique ID, the IP
      address of your mobile device, your mobile operating system, the type of
      mobile Internet browser you use, unique device identifiers and other
      diagnostic data.
      <p />
      <p>
        <strong>Location Data </strong>
      </p>
      <p>
        Your IP address may provide your approximate location. We may use and
        store this information about your location to provide features of our
        Service, to improve and customize our Service. If you disable location
        services when you use our Services through your device settings or
        masking your IP address, we will not know your location and our Services
        will not be impacted.
      </p>
      <p>
        <strong>Tracking and Cookies Data </strong>
      </p>
      <p>
        We use cookies and similar tracking technologies to track the activity
        on our Service and hold certain information.
      </p>
      <p>
        Cookies are files with small amount of data which may include an
        anonymous unique identifier. Cookies are sent to your browser from a
        website and stored on your device. Tracking technologies also used are
        beacons, tags, and scripts to collect and track information and to
        improve and analyze our Service.
      </p>
      <p>
        You can instruct your browser to refuse all cookies or to indicate when
        a cookie is being sent. At this time if you do not accept cookies most
        of our Services are expected to work. However, we cannot guarantee that
        all of our Services will work. Furthermore this may change in the future
        without notice.
      </p>
      <p>Examples of Cookies we use:</p>
      <p>- Session Cookies. We use Session Cookies to operate our Service.</p>
      <p>
        - Preference Cookies. We use Preference Cookies to remember your
        preferences and various settings.
      </p>
      <p>- Security Cookies. We use Security Cookies for security purposes.</p>
      <p>
        <strong>Use of Data </strong>
      </p>
      <p>LeadLine, LLC uses the collected data for various purposes:</p>
      <p>-To provide and maintain our Service</p>
      <p>-To notify you about changes to our Service</p>
      <p>
        -To allow you to participate in interactive features of our Service when
        you choose to do so
      </p>
      <p>-To provide customer support</p>
      <p>
        -To gather analysis or valuable information so that we can improve our
        Service
      </p>
      <p>-To monitor the usage of our Service</p>
      <p>-To detect, prevent and address technical issues</p>
      <p>
        -To provide you with news, special offers and general information about
        other goods, services and events which we offer that are similar to
        those that you have already purchased or enquired about unless you have
        opted not to receive such information.
      </p>
      <p>
        <strong>Retention of Data </strong>
      </p>
      <p>
        LeadLine, LLC will retain your Personal Data only for as long as is
        necessary for the purposes set out in this Privacy Policy. We will
        retain and use your Personal Data to the extent necessary to comply with
        our legal obligations (for example, if we are required to retain your
        data to comply with applicable laws), resolve disputes, and enforce our
        legal agreements and policies.
      </p>
      <p>
        LeadLine, LLC will also retain Usage Data for internal analysis
        purposes. Usage Data is generally retained for a shorter period of time,
        except when this data is used to strengthen the security or to improve
        the functionality of our Service, or we are legally obligated to retain
        this data for longer time periods.
      </p>
      <p>
        <strong>Transfer Of Data </strong>
      </p>
      <p>
        Your information, including Personal Data, may be transferred to — and
        maintained on — computers located outside of your state, province,
        country or other governmental jurisdiction where the data protection
        laws may differ than those from your jurisdiction.
      </p>
      <p>
        If you are located outside United States and choose to provide
        information to us, please note that we transfer the data, including
        Personal Data, to United States and process it there.
      </p>
      <p>
        Your consent to this Privacy Policy followed by your submission of such
        information represents your agreement to that transfer.
      </p>
      <p>
        LeadLine, LLC will take all steps reasonably necessary to ensure that
        your data is treated securely and in accordance with this Privacy Policy
        and no transfer of your Personal Data will take place to an organization
        or a country unless there are adequate controls in place including the
        security of your data and other personal information.
      </p>
      <h2> Disclosure of Data</h2>
      <p>
        <strong>Business Transaction </strong>
      </p>
      <p>
        If LeadLine, LLC is involved in a merger, acquisition or asset sale,
        your Personal Data may be transferred. We will provide notice before
        your Personal Data is transferred and becomes subject to a different
        Privacy Policy.
      </p>
      <p>
        <strong>Disclosure for Law Enforcement </strong>
      </p>
      <p>
        Under certain circumstances, LeadLine, LLC may be required to disclose
        your Personal Data if required to do so by law or in response to valid
        requests by public authorities (e.g. a court or a government agency).
      </p>
      <p>
        <strong>Legal Requirements </strong>
      </p>
      <p>
        LeadLine, LLC may disclose your Personal Data in the good faith belief
        that such action is necessary to:
      </p>
      <p>-To comply with a legal obligation</p>
      <p>-To protect and defend the rights or property of LeadLine, LLC</p>
      <p>
        {' '}
        -To prevent or investigate possible wrongdoing in connection with the
        Service
      </p>
      <p>
        -To protect the personal safety of users of the Service or the public
      </p>
      <p>-To protect against legal liability</p>
      <p>
        <strong>Security Of Data </strong>
      </p>
      <p>
        The security of your personal data and our Clients’ information is
        important to us, when you enter sensitive information, such as login
        credentials and credit card information, we encrypt the transmission of
        that information using secure socket layer technology (SSL).
      </p>
      <p>
        We follow generally accepted standards to protect the personal
        information submitted to us, both during transmission and once we
        receive it. No method of transmission over the Internet, or method of
        electronic storage is 100% secure. Therefore, we cannot guarantee its
        absolute security. If you have any questions about security on our
        website, you can{' '}
        <a href="mailto:support@onlinesalespro.com">contact us</a>.
      </p>
      <p>
        <strong>"Do Not Track" Signals </strong>
      </p>
      <p>
        We do not support Do Not Track ("DNT"). Do Not Track is a preference you
        can set in your web browser to inform websites that you do not want to
        be tracked. You can enable or disable Do Not Track by visiting the
        Preferences or Settings page of your web browser.
      </p>
      <p>
        <strong>Your Rights </strong>
      </p>
      <p>
        LeadLine, LLC aims to take reasonable steps to allow you to correct,
        amend, delete, or limit the use of your Personal Data.
      </p>
      <p>
        Whenever made possible, you can update your Personal Data directly
        within your account settings section. If you are unable to change your
        Personal Data, please contact us to make the required changes.
      </p>
      <p>
        If you wish to be informed what Personal Data we hold about you and if
        you want it to be removed from our systems, please contact us at{' '}
        <a href="mailto:support@onlinesalespro.com">
          support@onlinesalespro.com
        </a>
      </p>
      <p>In certain circumstances, you have the right:</p>
      <p>
        {' '}
        -To access and receive a copy of the Personal Data we hold about you
      </p>
      <p> -To rectify any Personal Data held about you that is inaccurate</p>
      <p> -To request the deletion of Personal Data held about you</p>
      <p>
        You have the right to data portability for the information you provide
        to LeadLine, LLC. You can request to obtain a copy of your Personal Data
        in a commonly used electronic format so that you can manage and move it.
      </p>
      <p>
        Please note that we may ask you to verify your identity before
        responding to such requests.
      </p>
      <p>
        <strong>Service Providers </strong>
      </p>
      <p>
        We may employ third party companies and individuals such as a credit
        card processing company or Live Chat service to facilitate our Service
        ("Service Providers"), to provide the Service on our behalf, to perform
        Service-related services or to assist us in analyzing how our Service is
        used.
      </p>
      <p>
        These third parties have access to your Personal Data only to perform
        these tasks on our behalf and are obligated not to disclose or use it
        for any other purpose.
      </p>
      <p>
        <strong>Analytics</strong>
      </p>
      <p>
        We may use third-party Service Providers to monitor and analyze the use
        of our Service.
      </p>
      <p>
        <strong>Google Analytics</strong>
      </p>
      <p>
        Google Analytics is a web analytics service offered by Google that
        tracks and reports website traffic. Google uses the data collected to
        track and monitor the use of our Service. This data is shared with other
        Google services. Google may use the collected data to contextualize and
        personalize the ads of its own advertising network.
      </p>
      <p>
        For more information on the privacy practices of Google, please visit
        the Google Privacy &amp; Terms web page:
        http://www.google.com/intl/en/policies/privacy/
      </p>
      <h2>Behavioral Remarketing </h2>
      <p>
        LeadLine, LLC uses remarketing services to advertise on third party
        websites to you after you visited our Service. We and our third-party
        vendors use cookies to inform, optimize and serve ads based on your past
        visits to our Service.
      </p>
      <p>
        <strong>Google AdWords</strong>
      </p>
      <p>
        Google also recommends installing the Google Analytics Opt-out Browser
      </p>
      <p>
        For more information on the privacy practices of Google, please visit
        the Google Privacy &amp; Terms web page:{' '}
        <a
          href="http://www.google.com/intl/en/policies/privacy/"
          target="_blank"
        >
          http://www.google.com/intl/en/policies/privacy/
        </a>
      </p>
      <p>
        <strong>Facebook</strong>
      </p>
      <p>Facebook remarketing service is provided by Facebook Inc.</p>
      <p>
        You can learn more about interest-based advertising from Facebook by
        visiting this page:
        <a href="https://www.facebook.com/help/164968693837950" target="_blank">
          https://www.facebook.com/help/164968693837950
        </a>
      </p>
      <p>
        To opt-out from Facebook's interest-based ads follow these instructions
        from Facebook:
        <a href="https://www.facebook.com/help/568137493302217" target="_blank">
          https://www.facebook.com/help/568137493302217
        </a>
      </p>
      <p>
        <strong>Social Media Features</strong>
      </p>
      <p>
        Our website includes social media features, such as the Facebook “Like”
        button. These features may collect your IP address and the page you are
        visiting on our website. It may also set a cookie to enable the features
        to function properly. Social media features are either hosted by a third
        party or hosted directly on our website. Your interactions with these
        features are governed by the privacy policy of the company providing it.
      </p>
      <p>
        <strong>Payments </strong>
      </p>
      <p>
        We may provide paid products and/or services within the Service. In that
        case, we use third-party services for payment processing (e.g. payment
        processors). We will not store or collect your payment card details.
        That information is provided directly to our third-party payment
        processors whose use of your personal information is governed by their
        Privacy Policy. These payment processors adhere to the standards set by
        PCI-DSS as managed by the PCI Security Standards Council, which is a
        joint effort of brands like Visa, Mastercard, American Express and
        Discover. PCI-DSS requirements help ensure the secure handling of
        payment information. The payment processors and carts we work with are:
      </p>
      <p>-Chargeover</p>
      <p>
        Their Privacy Policy can be viewed at
        <a href="https://chargeover.com/privacy-policy" target="_blank">
          https://chargeover.com/privacy-policy
        </a>
      </p>
      <p>-Stripe</p>
      <p>
        Their Privacy Policy can be viewed at
        <a href="https://stripe.com/us/privacy" target="_blank">
          https://stripe.com/us/privacy
        </a>{' '}
      </p>
      <p> -PayPal or Braintree</p>
      <p>
        Their Privacy Policy can be viewed at
        <a
          href="https://www.paypal.com/webapps/mpp/ua/privacy-full"
          target="_blank"
        >
          https://www.paypal.com/webapps/mpp/ua/privacy-full
        </a>
      </p>
      <p>-Authorize.net</p>
      <p>
        Their Privacy Policy can be viewed at
        <a href="https://www.authorize.net/company/privacy/" target="_blank">
          https://www.authorize.net/company/privacy/
        </a>
      </p>
      <p>
        <strong>Links To Other Sites </strong>
      </p>
      <p>
        Our Service may contain links to other sites that are not operated by
        us. If you click on a third party link, you will be directed to that
        third party's site. We strongly advise you to review the Privacy Policy
        of every site you visit.
      </p>
      <p>
        We have no control over and assume no responsibility for the content,
        privacy policies or practices of any third party sites or services.
      </p>
      <p>
        <strong>Log Files</strong>
      </p>
      <p>
        As is true of most websites, we gather certain information automatically
        and store it in log files. This information includes internet protocol
        (IP) addresses, browser type, internet service provider (ISP),
        referring/exit pages, the files viewed on our site (e.g., HTML pages,
        graphics, etc.), operating system, date/time stamp, and clickstream
        data.
      </p>
      <p>
        We use this information to analyze trends, administer our website, track
        visitors' movements around our website, and gather demographic
        information about our visitors as a whole. We do link this automatically
        collected data to other information we collect about our website
        visitors.
      </p>
      <p>
        <strong>Children's Privacy </strong>
      </p>
      <p>
        Our Service does not address anyone under the age of 13 ("Children"). We
        do not knowingly collect personally identifiable information from anyone
        under the age of 13. If you are a parent or guardian and you are aware
        that your Children has provided us with Personal Data, please contact
        us. If we become aware that we have collected Personal Data from
        children without verification of parental consent, we take steps to
        remove that information from our servers.
      </p>
      <p>
        <strong>Changes To This Privacy Policy </strong>
      </p>
      <p>
        We may update our Privacy Policy from time to time. We will notify you
        of any changes by posting the new Privacy Policy on this page.
      </p>
      <p>
        We will let you know via email and/or a prominent notice on our Service,
        prior to the change becoming effective and update the "effective date"
        at the top of this Privacy Policy.
      </p>
      <p>
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on this page.
      </p>
      <p>
        <strong>Contact Us </strong>
      </p>
      <p>
        If you have any questions about this Privacy Policy, please contact us:
      </p>
    </div>
  );
};
