import React from 'react';

export default () => {
  return (
    <div>
      {/* <div class="content-wrapper"> */}

      <h2>Terms and Conditions</h2>
      <p>
        This web page represents our Terms of Use, Terms and Conditions and Sale
        ("Agreement") regarding our website, https://onlinesalespro.com/
        ("Website"). It was last posted on May 1, 2018. The terms, "we" and
        "our" as used in this Agreement refer to Online Sales Pro by LeadLine,
        LLC.
      </p>

      <p>
        We may amend this Agreement at any time by posting the amended terms on
        our Website. We may or may not post notices on the homepage of our
        Website when such changes occur.
      </p>

      <p>
        We refer to this Agreement, our Privacy Policy accessible at
        http://onlinesalespro.com/privacy and any other terms, rules, or
        guidelines on our Website collectively as our "Legal Terms." You
        explicitly and implicitly agree to be bound by our Legal Terms each time
        you access our Website. If you do not wish to be so bound, please do not
        use or access our Website or Online Sales Pro mobile app.
      </p>

      <p>
        <strong>Limited License</strong>
      </p>

      <p>
        Online Sales Pro grants you a non-exclusive, non-transferable, revocable
        license to access and use our Website and mobile app in order for you to
        generate leads and access training and related services through our
        Website, strictly in accordance with our Legal Terms.
      </p>

      <p>
        <strong>Online Sales Pro Software &amp; App Subscriptions</strong>
      </p>
      <p>
        The service begins upon signup. Upon signup the login credentials you
        provided will immediately be functional, and those same credentials will
        be emailed to the address that you provided. Your login will be used for
        the web and mobile application. Your subscription will billed on a
        monthly basis approximately every 28 days, or annually if you are on an
        annual plan. Your billing statement will charge as Online Sales Pro or
        LeadLine LLC.
      </p>
      <p>
        You can cancel anytime by visiting your Account Settings page or contact
        support@onlinesalespro.com, or call 888-477-3345. Canceling your
        subscription will stop future charges but your service will continue
        through the end of your current billing period. You understand that if
        you cancel less than 1 day prior to the next billing date, you risk that
        your monthly payment may have already been processed, and that a refund
        will not be issued. I understand that canceling is solely my
        responsibility and the service is a recurring charge for the system and
        app access.
      </p>
      <p>
        This amount represents a license to use the software, website, landing
        pages and app. The software is offered “AS IS” with no warranty
        regarding its functionality, website availability, or the results
        obtained from use. All third party links added to the Online Sales Pro
        system by a subscriber within an online store are subject to approval.
        LeadLine LLC has the sole discretion to remove any third party links to
        content that we deem as potentially objectionable to our user base,
        including but not limited to adult material, gambling and drugs.
      </p>

      <p>
        All software, leads generated by software, and the database that
        contains said leads is property of LeadLine LLC. Your fee for membership
        is a license to use said software and the leads generated by the
        software. LeadLine LLC makes no representation of the success or
        potential success of its members, and the income that may or not be
        generated by using our leads and/or software.
      </p>

      <h2>Returns and Refunds Policy</h2>
      <p>
        <strong>Software Subscriptions (Monthly &amp; VIP Annual Plans)</strong>
      </p>
      <p>
        30-Day Guarantee: To ensure customer satisfaction of our software, we
        issue refunds for subscriptions within thirty (30) days of your initial
        purchase. Charges older than thirty (30) days are not eligible for a
        refund under any circumstances. You can cancel your subscription at
        anytime.
      </p>
      <p>
        We recommend contacting us for assistance if you experience any issues
        logging in, or using our products.
      </p>
      <p>
        If you have any questions about our Software Subscriptions Returns and
        Refunds Policy, please contact us:
      </p>

      <p />

      <p>
        <strong>
          Custom &amp; Service Products (MVP Software Add-On, Express Setup
          &amp; Courses)
        </strong>
      </p>

      <p>
        We do not issue refunds for Custom Products, Service Products or Boot
        Camp Courses once the order is confirmed and access/service has been
        delivered.
      </p>
      <p>
        We recommend contacting us for assistance if you experience any issues
        receiving or downloading our products.
      </p>
      <p>
        OSP Express Setup is a Service Product, and we do not offer refunds when
        the Express Setup has been completed.
      </p>
      <p>
        If you have any questions about our Custom &amp; Service Products
        returns and refunds policy, please contact us:
      </p>

      <p>
        <strong>Links to Third-Party Websites</strong>
      </p>
      <p>
        Our Website may contain links to Websites owned or operated by parties
        other than LeadLine, LLC. Such links are provided for your reference
        only. We do not monitor or control outside Websites and are not
        responsible for their content. Our inclusion of links to an outside
        Website does not imply any endorsement of the material on our Website
        or, unless expressly disclosed otherwise, any sponsorship, affiliation
        or association with its owner, operator or sponsor, nor does Online
        Sales Pro’s or LeadLine LLC’s inclusion of the links imply that Online
        Sales Pro is authorized to use any trade name, trademark, logo, legal or
        official seal, or copyrighted symbol that may be reflected in the linked
        Website.
      </p>

      <p>
        <strong>No Warranties; Exclusion of Liability; Indemnification</strong>
      </p>
      <p>
        OUR WEBSITE IS OPERATED BY LEADLINE, LLC ON AN "AS IS," "AS AVAILABLE"
        BASIS, WITHOUT REPRESENTATIONS OR WARRANTIES OF ANY KIND. TO THE FULLEST
        EXTENT PERMITTED BY LAW, LEADLINE, LLC SPECIFICALLY DISCLAIMS ALL
        WARRANTIES AND CONDITIONS OF ANY KIND, INCLUDING ALL IMPLIED WARRANTIES
        AND CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
        TITLE AND NONINFRINGEMENT FOR OUR WEBSITE AND ANY CONTRACTS AND SERVICES
        YOU PURCHASE THROUGH IT. LEADLINE, LLC SHALL NOT HAVE ANY LIABILITY OR
        RESPONSIBILITY FOR ANY ERRORS OR OMISSIONS IN THE CONTENT OF OUR
        WEBSITE, FOR CONTRACTS OR SERVICES SOLD THROUGH OUR WEBSITE, FOR YOUR
        ACTION OR INACTION IN CONNECTION WITH OUR WEBSITE OR FOR ANY DAMAGE TO
        YOUR COMPUTER OR DATA OR ANY OTHER DAMAGE YOU MAY INCUR IN CONNECTION
        WITH OUR WEBSITE. YOUR USE OF OUR WEBSITE AND ANY CONTRACTS OR SERVICES
        ARE AT YOUR OWN RISK. IN NO EVENT SHALL EITHER LEADLINE OR THEIR AGENTS
        OR AFFILIATES BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL,
        SPECIAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN ANY WAY CONNECTED
        WITH THE USE OF OUR WEBSITE, CONTRACTS AND SERVICES PURCHASED THROUGH
        OUR WEBSITE, THE DELAY OR INABILITY TO USE OUR WEBSITE OR OTHERWISE
        ARISING IN CONNECTION WITH OUR WEBSITE, CONTRACTS OR RELATED SERVICES,
        WHETHER BASED ON CONTRACT, TORT, STRICT LIABILITY OR OTHERWISE, EVEN IF
        ADVISED OF THE POSSIBILITY OF ANY SUCH DAMAGES. IN NO EVENT SHALL
        LEADLINE, LLC BE LIABLE FOR ANY DAMAGE CLAIM EXCEEDING THE AMOUNT PAID
        BY YOU TO LEADLINE, LLC FOR THE TRANSACTION GIVING RISE TO SUCH DAMAGE
        CLAIM.
      </p>
      <p>
        SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF
        INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE EXCLUSION MAY NOT
        APPLY TO YOU.
      </p>
      <p>
        WITHOUT LIMITING THE FOREGOING, LEADLINE, LLC DOES NOT REPRESENT OR
        WARRANT THAT THE INFORMATION ON THE WEBSITE IS ACCURATE, COMPLETE,
        RELIABLE, USEFUL, TIMELY OR CURRENT OR THAT OUR WEBSITE WILL OPERATE
        WITHOUT INTERRUPTION OR ERROR.
      </p>

      <p>
        <strong>Indemnification</strong>
      </p>
      <p>
        You agree to defend, indemnify and hold Online Sales Pro and LeadLine,
        LLC harmless from and against any and all claims, damages, costs and
        expenses, including attorneys' fees, arising from or related to your use
        of our Website or any Contracts or Services you purchase through it.
      </p>
      <p>
        <strong>Contact Us</strong>
      </p>
      <p>If you have any questions, please contact us:</p>

      {/* </div> */}
    </div>
  );
};
